### ISSUE TITLE
Rent page UI/UX - kate

### ISSUE THREAD

**Issue by kilibe** [veradefi/vera.financial#1]
add "BUSD" as unit after Daily Rent Price and "Collateral";
![image](https://user-images.githubusercontent.com/87932238/148460636-bb234e77-c5a0-44e0-af42-8471fd05119e.png)

**Comment by DLekocaj888** [comment]
Issue fixed.

**Comment by veracomm** [comment]
@kilibe  please test this again and close the issue

**Comment by veracomm** [comment]
@DLekocaj888 issue is not fixed, price doesn't show BUSD on the screen.

**Comment by veracomm** [comment]
@DLekocaj888 Update please?

**Comment by DLekocaj888** [comment]
Already updated. Check pls.

**Comment by veracomm** [comment]
Hi @DLekocaj888 Ticker for Vera payment type is showing as BUSD and ETH symbol is shown.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/95225639/152518762-88b756ba-144a-4632-9947-da49e7a36525.png">

**Comment by veracomm** [comment]
@DLekocaj888 and @arbach is this fixed?

**Comment by hardik0207** [comment]
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/10892303/155747791-fdd8ed35-bc6b-4143-a5b5-d81452eee9fe.png">
