### ISSUE TITLE
filter by contract

### ISSUE THREAD

**Issue by jessieyeahh** [veradefi/vera.financial#10]
What does filter by contract mean? Do you mean by collection? Should we change it to filter by collection?

**Comment by DLekocaj888** [comment]
@veracomm Those are contract. Its a filter by contract.

**Comment by DLekocaj888** [comment]
> What does filter by contract mean? Do you mean by collection? Should we change it to filter by collection?

@jessieyeahh @veracomm Those are contracts. It's a filter by contract.

**Comment by veracomm** [comment]
@DLekocaj888  those are contracts in Blockchain you're right, may be there needs to be a filter by collection which filters by collection name
