### ISSUE TITLE
Can't lend a single NFT or lend multiple NFTs

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#13]
Connected the wallet via Wallet Connect (not sure if this makes any difference)

Tried a single lending but the transaction failed
Tx - https://bscscan.com/tx/0x1ad13deb5427efb655d283bc29d44db13bc5ff887ff7bf0fc9556f8f2a229731

Tried a multi lending, transaction failed again
Tx - https://bscscan.com/tx/0xcd445c1882a4b4a7509cd41f46b4080184d425f9b55b2aefa7dbf21140b5b90f

URL - https://rent.vera.financial/lend-details/82/0xb877af5ba1d638597ca22e0b1b84fd6ca60206ec

Can this be looked at ASAP? Blocks me from testing most of the features

**Comment by DLekocaj888** [comment]
Issue fixed.

**Comment by veracomm** [comment]
Can lend multiple NFTs now, issue was with NFTs
