### ISSUE TITLE
Connected via Wallet Connect - getting weird message at the top of the site and can't rent

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#14]
![image](https://user-images.githubusercontent.com/95225639/150124751-554ff73c-b6fd-4ede-8a63-1a37b60878b6.png)

Connected via Wallet Connect on BSC network:

1. getting weird message at the top of the site - says connected to Unknown
2. and can't rent - All Rent buttons are disabled, there is enough BNB balance in my wallet

![image](https://user-images.githubusercontent.com/95225639/150124921-cb99ae63-2951-48ea-935b-08fc2122d516.png)

**Comment by DLekocaj888** [comment]
Issue fixed.

**Comment by veracomm** [comment]
@DLekocaj888 weird message is gone, stil can't rent due to another issue so closing this
