### ISSUE TITLE
Dashboard - items on rent show wrong currency

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#17]
![image](https://user-images.githubusercontent.com/95225639/150234338-5a422ee6-6e2b-482c-815a-8885b55b26f8.png)

**Wallet:** 0x95B3ee7c46b2675c3f0eC0Cf3c6189f8dF314D18
**Lend Transactions:**
Approval - 0xb0b5c3a9b05f1b55a96bedd2b8263ea5f828a074c3d4fc1a3722d2ee4e7ec747
Lend - https://bscscan.com/tx/0x1a74675400139123a400d2f39fc99d72fb67912f1cf21cea79b441540f3701ba

**Description:**

I lend a NFT in Vera token. Set collateral and price to 0.01 VERA. However after lending, Dashboard shows prices in ETH 0.01. I suspect  only the icon for Vera is show incorrectly as ETH.

Additionally, the labels/headings on the Dashboard are not bold (Lend and Rent pages have bold headings). Headings on the page definitely looks cluttered when there is no NFT under Lend or Rent section.

![image](https://user-images.githubusercontent.com/95225639/150235950-58a1f4e3-fe6d-4a97-9cb4-fc01c71d4bf4.png)

**Comment by DLekocaj888** [comment]
Issue fixed.
