### ISSUE TITLE
NFT didn't return to wallet after lend and cancel lending

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#18]
**Cancel lease transaction:**

https://bscscan.com/tx/0x1a74675400139123a400d2f39fc99d72fb67912f1cf21cea79b441540f3701ba

**Steps followed:**

1. Connect to rent.vera.financial via Metamask desktop extension
2. Lend a NFT (nft contract and tokenID are in the transaction above)
3. Confirm the NFT is available on the dashboard under 'Lend Dashboard' section
4. Cancel Lend
5. NFT didn't return back to my wallet

**NFT is in the contract now**, check history of the NFT here - https://bscscan.com/token/0xf5db804101d8600c26598a1ba465166c33cdaa4b?a=149689

**Comment by DLekocaj888** [comment]
@veracomm Could not reproduce this bug and it's coming from Moralis, so might be there server issue.

**Comment by veracomm** [comment]
@DLekocaj888 and @arbach I can't test this yet as cancelling lending is gas'ed at 0.38 BNB, tried a few times.

Could you guys try at your end and see if the gas fee is that high?

![image](https://user-images.githubusercontent.com/95225639/150625400-61d6bfc7-87dc-44a8-b09d-2f8030ad821c.png)

**Comment by veracomm** [comment]
@arbach & @DLekocaj888 I can't replicate this as the cancel lending doesn't work me (may be issue is on my side)

**Comment by UmairJanjua6** [comment]
![image](https://user-images.githubusercontent.com/56170485/150733335-83dd14ac-a3cf-4725-8983-48274f9ff37b.png)

NFT was returned to the user, There's few issues in UI, it will be resolved soon

**Comment by veracomm** [comment]
> ![image](https://user-images.githubusercontent.com/56170485/150733335-83dd14ac-a3cf-4725-8983-48274f9ff37b.png)
> 
> NFT was returned to the user, There's few issues in UI, it will be resolved soon

@UmairJanjua6 yes, it looks that way, but if you look at the next transaction, it went back to contract when I cancelled Rent for a different NFT.

![image](https://user-images.githubusercontent.com/95225639/150738355-51bd2d44-c32e-4997-8654-68892a295cda.png)

**Comment by UmairJanjua6** [comment]
https://ibb.co/3mm97NR Please check this.

**Comment by veracomm** [comment]
I just tried with a new wallet and the NFT returned to wallet after cancel lending.

@arbach @UmairJanjua6 @DLekocaj888
