### ISSUE TITLE
Rent duration on rent screen and rent payment screen don't match

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#19]
Rent screen:

![image](https://user-images.githubusercontent.com/95225639/150624811-6e6f048e-60f0-4331-8530-d58e205a4176.png)

Trying to rent it but duration is in Minutes (is this a new feature?): Duration doesn't match:

1. Duration is shown in minutes which is wrong
2. Price is some random $234 in USD. Is this even a real screen looks like a mock-up screen was pushed to Mainnet?????

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/95225639/150624852-a4da60e2-0b69-4788-8af2-492957486740.png">

**Comment by DLekocaj888** [comment]
This is fixed.
