### ISSUE TITLE
Lend page - UI/UX

### ISSUE THREAD

**Issue by kilibe** [veradefi/vera.financial#2]
My 1st and 2nd NFT items' boxes has different length
![image](https://user-images.githubusercontent.com/87932238/148460837-012599de-bbfa-4f95-b5af-ddf640f295da.png)

**Comment by DLekocaj888** [comment]
Issue resolved.

**Comment by veracomm** [comment]
Hey @kilibe , could you test this issue again please?

**Comment by veracomm** [comment]
![image](https://user-images.githubusercontent.com/95225639/151722082-4819a7bb-21c4-435f-a484-d332a6b81ac8.png)

Issue has been fixed on Rental page.
Lend page doesn't show the full details anymore.
