### ISSUE TITLE
[BSC NETWORK] High BNB gas fees when trying to 'Stop Lending' NFT

### ISSUE THREAD

**Issue by joshjvera** [veradefi/vera.financial#21]
I used bulk listing to list these 2 NFTs for lending out.
Now that I'm trying to stop lending either one of them, the gas fees are 0.38 BNB ($130+ USD!)
Here is successful leasing transaction id -  0x60dcfb39f09bd56d3ae1b4e1482ecbead75b11043bfce2611aef84cae4ea2184

See screenshot of high fee attached below.

![veraissue](https://user-images.githubusercontent.com/98233642/150652081-b5484cfb-f368-4e57-8477-f308ccd4e746.png)

**Comment by joshjvera** [comment]
@arbach @veracommThe transaction id is 0x60dcfb39f09bd56d3ae1b4e1482ecbead75b11043bfce2611aef84cae4ea2184
for successful leasing out.

**Comment by veracomm** [comment]
@arbach I tried to lend one of the new NFTs you sent and tried to cancel Lend, still the gas fee is 0.37BNB to cancel lend.

**Comment by veracomm** [comment]
https://bscscan.com/address/0xcaee211e20f199352933cc390a0f448eaa8f3c0a

I tried this action with a new wallet and seems fine to cancel lend. So closing this issue.

**Comment by veracomm** [comment]
I have reopened this as this is still happening to @joshjvera and Alex H.  May be it's related to double lending but still an issue for a few.

**Comment by joshjvera** [comment]
@veracomm @arbach here is a reference video. I created a new wallet and attempted to stop lending a Voshi nft. .37 BNB gas fee again.

https://loom.com/share/241e63eccaa2427fa21fe19d33c0a0df

**Comment by arbach** [comment]
can we test again, we have new version since this last was reported. @joshjvera
