### ISSUE TITLE
Change BSC logo to the correct BSC one

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#23]
![image](https://user-images.githubusercontent.com/95225639/150780509-c69eacc0-75c1-45fd-82c5-2f9c912778c6.png)

**Comment by veracomm** [comment]
@ceciveloso not sure if you need to fix this in Figma

**Comment by DLekocaj888** [comment]
@veracomm @ceciveloso pls provide the right logo in figma first.

**Comment by veracomm** [comment]
> @veracomm @ceciveloso pls provide the right logo in figma first.

https://download.logo.wine/logo/Binance/Binance-Icon-Logo.wine.png

@DLekocaj888

**Comment by ceciveloso** [comment]
@veracomm done!

**Comment by hardik0207** [comment]
Added BSC Logo

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/10892303/157033030-24f93535-1ee6-44f1-9915-3403830afaed.png">
