### ISSUE TITLE
Polygon rental issue

### ISSUE THREAD

**Issue by AlexHra** [veradefi/vera.financial#24]
When trying to lend on Polygon, it displays an error. 

Steps that I do: 
1) Select NFT and enter necessary details (1 day, 1 USD collateral and 1 USD price) and press lend. 
2) After that I confirm a transaction in metamask. It displays the following when confirming with "unknown processing time"
<img width="1076" alt="Screenshot 2022-01-26 at 10 13 30" src="https://user-images.githubusercontent.com/97300763/151136062-1c00e7da-4a88-40e3-a95c-904676a50343.png">

3) After that the screen saying "approving, Dont close the page..." stays on for 1-2 minutes. In the meantime my transaction is Pending
<img width="336" alt="Screenshot 2022-01-26 at 10 14 03" src="https://user-images.githubusercontent.com/97300763/151136422-4bea488a-06f2-48f1-8f33-557a57c4d602.png">

4) Than is displays an error message
<img width="750" alt="Screenshot 2022-01-26 at 10 15 46" src="https://user-images.githubusercontent.com/97300763/151136327-f4fa1c5e-bbd7-4dda-a294-fb189189640a.png">

5) My transaction is still pending, despite the fact that the rental didn't go through

Transaction ID: 0x87a6916b273489a27176829b0bdb064f421c171b55530ce7bc2168d1dd264979

**Comment by DLekocaj888** [comment]
@veracomm this issue is due to network congestion.

**Comment by veracomm** [comment]
@DLekocaj888 I am still getting the same issue on multi-lending (same steps as described above)

Transaction takes a while and the site throws an error before the transaction is finished.

**Metmask node used for Polygon:**

https://polygon-rpc.com/
chain id - 137

**Console Error:**
error Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (2.113e6fc4.chunk.js:2:2590905)
    at 2.113e6fc4.chunk.js:2:429371

**Comment by arbach** [comment]
> @veracomm this issue is due to network congestion. Yesterday, the polygon network was congested, maybe that's the reason for the delayed transaction confirmation. The transaction is successful now.

This
