### ISSUE TITLE
Filter by contract list is different when a wallet is connected vs before connecting a wallet

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#29]
**Wallet connected:**

![image](https://user-images.githubusercontent.com/95225639/152679856-34bb44a8-85c9-47f2-897f-ca709d0fb06f.png)

**Wallet not connected**

![image](https://user-images.githubusercontent.com/95225639/152679897-001fbdbb-7c51-4b9a-b60a-9cfbc3f08e35.png)

**Comment by arbach** [comment]
when user is not connected we fetch contact for every network.. once connected we fetch for particular network

**Comment by veracomm** [comment]
@arbach and @DLekocaj888 - difference between after connecting wallet and before is NFTs paid by Vera.

So this is still a bug, once you connect a BSC wallet, only BUSD payment type NFTs are shown. NFTs rented with Vera are missing from the Rent screen.

**Comment by veracomm** [comment]
I got it now, those that don't appear are my own nfts. all good!
