### ISSUE TITLE
Fix collateral typo 

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#31]
![image](https://user-images.githubusercontent.com/95225639/154015141-00c41873-6d9c-4cb6-b1bf-5db9100b691d.png)

Worth checking the entire project for the typo and fix it.

**Comment by veracomm** [comment]
@DLekocaj888 and @arbach is this fixed?

**Comment by hardik0207** [comment]
This issue has been fixed and deployed on Mainnet

**Comment by DLekocaj888** [comment]
@veracomm pls close this one

**Comment by arbach** [comment]
fixed
