### ISSUE TITLE
[BSC] Binopoly NFTs are not rendered on the listing screen

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#32]
Contract address - 0xe5ffde144592121195d43fdfb3621fc7530c0040

![image](https://user-images.githubusercontent.com/95225639/155677373-1bcabafe-2fb2-4ad4-ae57-14e7657e424e.png)

**Comment by veracomm** [comment]
@arbach @DLekocaj888 

This NFT renders image on Nftrade but not on our rental marketplace

https://nftrade.com/assets/bsc/0xe5ffde144592121195d43fdfb3621fc7530c0040/11

**Comment by hardik0207** [comment]
@veracomm  This issue has been fixed and deployed

**Comment by DLekocaj888** [comment]
![image](https://user-images.githubusercontent.com/98027109/158563320-2d1c6051-49f0-4205-9b9e-c58cc2ce8716.png)
Im closing this one.
