### ISSUE TITLE
2 Listed NFTs don’t appear on Lend Dashboard 

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#33]
Hi team,

Wallet - 0x6bd47b65ed457b6a6ee69bd1c42fee4e7d1ec07d

Listed 3 NFTs for lease/lending on Polygon network. But the dashboard on Vera only displays only 1 NFT out of the 3 listed for lending.

Tx of the NFT that appears:

0x241b5ce7cfa363a4231f2123ca31d18ccad4617e3e93dc6c843c8618b85771fd

Tax hashes of the NFTs that don’t appear:

0x415010a5bc4732a8133172be932e5c72b758e25750fd0163116ddbe2c30f9fd7

0xe451c1145591f29f7d1e093d48874444a4476cfa154a05658610b521665cadd6

**Comment by veracomm** [comment]
@DLekocaj888 and @arbach - any updates?

**Comment by arbach** [comment]
@veracomm  can you have them check again ?

**Comment by veracomm** [comment]
Hey @arbach and @DLekocaj888 

The two that weren't appearing are now appearing.

However, 2 other NFTs are not appearing now. One is Polygon and the other one is BSC NFT. Contract addresses below:

0x241b5ce7cfa363a4231f2123ca31d18ccad4617e3e93dc6c843c8618b85771fd

0x30749d79020df3ba7ea7af0a6e061bd09c30abccab3957170ae08cf65af253bc

**Comment by veracomm** [comment]
Hey @arbach  and @DLekocaj888 

I have had lengthy chats with this guy and checked the bscscan and polyscan transactions.

It comes down to 2 poly NFTs and 1 BSC NFTs are not accounted for. That is, listed for lease but not showing on his dashboard for him to cancel lending.

**2 poly NFT lease transaction ids:**
[0x241b5ce7cfa363a4231f2123ca31d18ccad4617e3e93dc6c843c8618b85771fd](https://polygonscan.com/tx/0x241b5ce7cfa363a4231f2123ca31d18ccad4617e3e93dc6c843c8618b85771fd)
[0xe451c1145591f29f7d1e093d48874444a4476cfa154a05658610b521665cadd6](https://polygonscan.com/tx/0xe451c1145591f29f7d1e093d48874444a4476cfa154a05658610b521665cadd6)

**1 BSC NFT lease transaction id**
https://bscscan.com/tx/0x45930e7f0828a429dd0eda93d04fc3a2d233c51749820688b621c816aa17ee82

It's been a very long time with this issue. Customer is loosing his patience and started complaining on socials that his NFTs are missing. Can you please look at resolving them the earliest, thank you!

**Comment by hardik0207** [comment]
@veracomm fixed the issues, please verify and let us know

**Comment by arbach** [comment]
@veracomm  can you please check ?

**Comment by veracomm** [comment]
I have asked the end user. No response from him yet.

**Comment by veracomm** [comment]
@hardik0207  and @arbach 

User has replied eventually.

He can see 3 out of 4 missing NFTs.

He claims that he had cancelled the listing for 1 NFT and the NFT didn't return to his Wallet? Can you please check.

https://polygonscan.com/tx/0xe451c1145591f29f7d1e093d48874444a4476cfa154a05658610b521665cadd6

**Comment by khanoc** [comment]
this NFT is in leased section 
![image](https://user-images.githubusercontent.com/102341806/161440656-8b520ab6-95dc-48f6-9e77-d010054ef5aa.png)
