### ISSUE TITLE
Metamask matching the chosen Chain

### ISSUE THREAD

**Issue by AlexHra** [veradefi/vera.financial#4]
2 things:
1) When the Chain selected on the website doesn't match the one in Metamask, can we make it notify users? Like in Pancakeswap - see screenshot
<img width="1413" alt="Screenshot 2022-01-07 at 16 37 08" src="https://user-images.githubusercontent.com/97300763/148568573-451e6898-8050-4a98-b03c-a9a4d5c7085e.png">

2) When I reload a page, it always goes back to Eth Chain. Can we make it stay on the same chain when the page is reloaded?

**Comment by DLekocaj888** [comment]
Issue Fixed.

**Comment by veracomm** [comment]
@AlexHra  please confirm that this issue is fixed so we can close it.
