### ISSUE TITLE
Access to NFT Details

### ISSUE THREAD

**Issue by AlexHra** [veradefi/vera.financial#7]
Some NFTs cannot be seen fully when on the main page (see screenshot attached). To access the full view and details about the rental user would have to press "Rent Now" currently. Can we add functionality, so that when user clicks on the NFT, he can access details as well?
<img width="1346" alt="Screenshot 2022-01-19 at 07 46 22" src="https://user-images.githubusercontent.com/97300763/150071493-153ba5c3-ee0b-46f9-bd54-0a1d38b37e53.png">

**Comment by veracomm** [comment]
@ceciveloso Hey, has this been updated in the Figma?

@DLekocaj888  would like to confirm

**Comment by ceciveloso** [comment]
I'll check it

**Comment by ceciveloso** [comment]
@veracomm @DLekocaj888 done

**Comment by hardik0207** [comment]
Added new page for NFT details

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/10892303/157032235-c864313e-eb6c-439b-aa81-95c2ed6d0737.png">

**Comment by veracomm** [comment]
> Added new page for NFT details
> 
> <img alt="image" width="1308" src="https://user-images.githubusercontent.com/10892303/157032235-c864313e-eb6c-439b-aa81-95c2ed6d0737.png">

@hardik0207 and @DLekocaj888 - I can't see this change in the mainnet yet. When can I expect this change deployed?

**Comment by hardik0207** [comment]
this changes has been deployed on Mainnet

**Comment by veracomm** [comment]
Tested in prod
