### ISSUE TITLE
Add additional filters

### ISSUE THREAD

**Issue by jessieyeahh** [veradefi/vera.financial#9]
Add "Price: Low to High"
Add "Price: High to Low"

**Comment by DLekocaj888** [comment]
Issue fixed.

**Comment by veracomm** [comment]
@jessieyeahh - please confirm whether this issue has been fixed and close the issue

**Comment by veracomm** [comment]
@DLekocaj888 Do these filters factor in the different payment options liek BUSD and Vera etc?

Seems to be working
